name: CD - Deploy to Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to nginx folder
        run: |
          cp index.html /var/www/eval-devops/index.html
          systemctl reload nginx
